Modify web search
parsa-epfl/cloudsuite pull request #373
Opened 2022-09-01 16:47 UTC by aansaarii

This PR updates the web-search benchmark. The highlight of the changes is as follows:
1. The Solr engine is updated from 6.6 to 9.0. 
2. The index file is changed. The old one was based on Lucene 5. The new index is based on Lucene 9. 
3. Some minor modifications to the client image.

2022-09-02 10:10 UTC, Xusine1131 requested changes

2022-09-02 10:10 UTC, Xusine1131 commented on docs/benchmarks/web-search.md
> +  $ docker run --name web_search_dataset cloudsuite/web-search:dataset
Can you format all the terminal commands using the way below?

```
$ docker run --name web_search_dataset cloudsuite/web-search:dataset
```

Just using three \` to create a code block.

2022-09-02 10:10 UTC, Xusine1131 commented on docs/benchmarks/web-search.md
>  The following command will start the client node and run the benchmark. The `server_address` refers to the IP address, in brackets (e.g., "172.19.0.2"), of the index node that receives the client req
I think it's better to give the command prototype first, like:
```
$ docker run -it --name web_search_client --net host cloudsuite/web-search:client <server_address> <number of concurrent clients>  <The ramp up time in secod> <the ramp down time in second> <measurement time in second>

And then, give your example by saying "Here is an example where we use 50 clients, 90-second warm up time, 60-second ramp-down time and 60-second measurement time"
```

2022-09-02 10:11 UTC, Xusine1131 commented
Also, can you please fix the spell check error by adding new words to the `.wordlist`?

2022-09-02 12:46 UTC, aansaarii commented on benchmarks/web-search/client/files/search/deploy/run.xml~
> +<?xml version="1.0" encoding="UTF-8"?>
It was there by default. I think we can remove it.

2022-09-02 12:50 UTC, aansaarii commented on benchmarks/web-search/client/files/search/distributions/Ziphian.java
> +/* CloudSuite4.0 Benchmark Suite
The Dockerfile specifies the distribution [here](https://github.com/parsa-epfl/cloudsuite/blob/modify_web_search/benchmarks/web-search/client/Dockerfile#L13). Then, the requested distribution is copied to the build directory [here](https://github.com/parsa-epfl/cloudsuite/blob/modify_web_search/benchmarks/web-search/client/docker-entrypoint.sh#L22). BTW, I have not tested the other distribution that is `Random.java`.

2022-09-02 14:00 UTC, aansaarii commented
Thanks for your feedback @Xusine1131.
Please check the latest pushes.

2022-09-02 14:31 UTC, Xusine1131 commented on benchmarks/web-search/client/files/search/distributions/Ziphian.java
> +/* CloudSuite4.0 Benchmark Suite
Should we mention that we can have a different distribution in the document? I think the distribution is important for doing research.

2022-09-07 18:01 UTC, Xusine1131 approved these changes

2022-09-07 18:01 UTC, merged